## Produtos

Tarefas: 

- Parte 1 — Padronize os nomes das categorias de produtos em: eletrônicos, propulsão e ancoragem.
- Parte 2 — Converta os valores para o tipo numérico.
- Parte 3 — Remova as duplicatas.

In [14]:
import pandas as pd

#Visualizando os dados
df = pd.read_csv('../datasets/produtos_raw.csv')
df.tail()

,name,price,code,actual_category
152,Corrente Delta Vox Ion,R$ 495.98,146,ancoragem
153,Corrente Danforth Force Leviathan Impulse,R$ 3030.08,147,Ancoraguem
154,Âncora Delta Force Barracuda Mako,R$ 4785.56,148,Ancorajem
155,Cabo de Nylon Bruce Core,R$ 1163.62,149,Ancoragem
156,Cabo de Nylon Danforth Magnum Vox,R$ 1645.66,150,Ancorajem

In [15]:
#Normalizando a categoria dos produtos
def normalizar_categoria(valor):
    # remove espaços internos, converte para minúsculo e tira acentos
    v = valor.replace(' ', '').lower()
    v = v.replace('ô', 'o').replace('ã', 'a').replace('ç', 'c')

    if 'eletr' in v:
        return 'eletrônicos'
    elif 'prop' in v:
        return 'propulsão'
    elif 'ancor' in v or 'encor' in v:
        return 'ancoragem'
    else:
        return 'desconhecido'

df['actual_category'] = df['actual_category'].apply(normalizar_categoria)
df['actual_category'].value_counts()
df.head()

                             name        price  code actual_category
0     Transponder AIS Maré Magnum  R$ 33122.52     1     eletrônicos
1       Transponder Furuno Marlin  R$ 13998.15     2     eletrônicos
2    Radar Furuno Pulse Leviathan   R$ 9024.19     3     eletrônicos
3       Rádio AIS Hydro Tidal Zen   R$ 3381.88     4     eletrônicos
4  Piloto Automático Furuno Storm  R$ 23669.01     5     eletrônicos

In [16]:
#Converta os valores para o tipo numérico
df['price'] = (
    df['price']
    .str.replace('R$', '', regex=False)
    .str.strip()
    .astype(float)
)

df.dtypes

name                   str
price              float64
code                 int64
actual_category        str
dtype: object

In [17]:
# Removendo linhas duplicadas
antes = len(df)
df = df.drop_duplicates()
depois = len(df)

print(f"Linhas removidas: {antes - depois}")
print(f"Linhas restantes: {depois}")

Linhas removidas: 7
Linhas restantes: 150

In [19]:
df.head(100)

,name,price,code,actual_category
0,Transponder AIS Maré Magnum,33122.52,1,eletrônicos
1,Transponder Furuno Marlin,13998.15,2,eletrônicos
2,Radar Furuno Pulse Leviathan,9024.19,3,eletrônicos
3,Rádio AIS Hydro Tidal Zen,3381.88,4,eletrônicos
4,Piloto Automático Furuno Storm,23669.01,5,eletrônicos
...,...,...,...,...
99,Motor de Popa Tohatsu Boost Swift 126HP,70620.84,96,propulsão
100,Motor de Popa Tohatsu Evo 168HP,135335.07,97,propulsão
101,Motor Diesel Parsun Velocity Abyss Orca 235HP,79361.13,98,propulsão
102,Motor Elétrico Honda Flux Ultra 273HP,107266.66,99,propulsão
103,Motor Elétrico Honda Vector Abyss 220HP,104600.24,100,propulsão